### PR TITLE
Try to check if PR is not automatically merged

### PR DESCRIPTION
**Pull request by LanderU**
Signed-off-by: LanderU <lander.usategui@gmail.com>

### CODE REVIEW

**Comment by LanderU** [comment]
Confirmed, closing.

**Comment by vmayoral** [comment]
Note @LanderU we need to add the `invalid` label, otherwise it'll show up in the general statistics auto-generated in the README.

**Comment by LanderU** [comment]
Ups, sorry.

**Comment by vmayoral** [comment]
No worries!

**Pull request closed without merging**
