### PR TITLE
Fix setup.py to install deps from git

### LINKED ISSUE #3339: Download RVD external dependencies on setup.py instead of installing them manually
Hi Alias Robotics team!

I've found a way to install https://github.com/aliasrobotics/RVD/blob/master/setup.py#L33-L34, without cloning and installing it by hand.

Would you accept this change if I send the PR?

It would be great to have a issue template for tool features and not only for bugs/vulnerabilities, etc.

### PR DESCRIPTION
**Pull request by LanderU**
* Update requests version to 2.23.0 to avoid conflicts with pycvesearch
* Install pycvesearch/cvsslib in setup.py

Closes #3339

Signed-off-by: LanderU <lander.usategui@gmail.com>

### CODE REVIEW

**Comment by vmayoral** [comment]
@LanderU and @unaithetutamatumatu, please remeber to mark PRs as `contribution` and `invalid` labels. Otherwise we mess up the automation that's behind with the `rvd` tooling.

Just a minor reminder.

**Comment by vmayoral** [comment]
By the way, this is awesome, thanks @LanderU

**Comment by LanderU** [comment]
@vmayoral @unaithetutamatumatu, I cannot add labels in PR and either on issues. This is why I ping you here.

**Comment by vmayoral** [comment]
> @vmayoral @unaithetutamatumatu, I cannot add labels in PR and either on issues. This is why I ping you here.

Makes sense then and sorry, I wasn't aware of that. I gave you rights right now. That should do it for future situations.

**Pull request merged**
